name: Main Workflow

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [trigger-event]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Cucumber Tag'
        required: true
        default: '@defaultTag'
      unique_id:
        description: 'Unique ID'
        required: true
        default: '12345'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Cucumber tests with dynamic parameters
        run: |
          echo "Running Cucumber tests with tag: ${{ github.event.inputs.tag }} and unique ID: ${{ github.event.inputs.unique_id }}"
          mvn test -Dcucumber.filter.tags="${{ github.event.inputs.tag }}" -Dunique.id="${{ github.event.inputs.unique_id }}"
