
name: Main Workflow

on:
  push:
    branches:
      - main
  repository_dispatch: # Add this line to listen for repository dispatch events
    types: [trigger-event] # You can specify a custom type

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a script
        run: echo "Hello, world!"
        
      - name: Compile Java code
        run: |
          mkdir -p out
          javac -d out src/com/hello/Addition.java

      - name: Run Java main class
        run: |
          java -cp out com.hello.Addition
