name: Run Java Class with Parameter
 
on:
  repository_dispatch: # Add this line to listen for repository dispatch events
    types: [test]
  workflow_dispatch:
    inputs:
      param:
        description: 'Dynamic parameter'
        required: true
        default: 'default_value'
 
jobs:
  run-java:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
 
 
 
    - name: Run Java class with parameter
      run: echo "Testing ---"${{ github.event.inputs.param }}"---Testing"
